/**
 * Bundle the Fluid handler to dist/web.mjs.
 *
 * Vercel Fluid cannot run the TypeScript workspace via runtime tsx (tsx's
 * CJS helper is missing from the lambda). tsc cannot emit this graph because
 * workspace imports use .ts specifiers (TS5097). esbuild inlines
 * @cubiczan/shared and leaves node: builtins external.
 */
import { mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outfile = join(root, "dist/web.mjs");

mkdirSync(dirname(outfile), { recursive: true });

await build({
  absWorkingDir: root,
  entryPoints: [join(root, "packages/governed-mcp-gateway/src/web.ts")],
  outfile,
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  logLevel: "info",
  legalComments: "none",
  banner: {
    js: "/* governed-mcp-gateway Fluid handler — generated by scripts/build-vercel.mjs */",
  },
});
